sudo: required
services:
  - docker
# Build test version of React project (client) ./client directory to look for Dockerfile.dev and build image
before_install:
  - docker build -t frontend-test -f ./client/Dockerfile.dev ./client

# Run tests
script:
  - docker run -e CI=true frontend-test npm test
 
after_success: 
  - docker build -t complexfib-client ./client
  - docker build -t complexfib-nginx ./nginx
  - docker build -t complexfib-server ./server
  - docker build -t complexfib-worker ./worker
  # Log in to the docker CLI
  # | is a pipe, i.e. shift + \ on keyboard
  # echo part is taken and piped as input to the next command after | 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # need to tag images before pushing to docker hub
  - docker tag complexfib-client $DOCKER_ID/complexfib-client
  - docker tag complexfib-nginx $DOCKER_ID/complexfib-nginx
  - docker tag complexfib-server $DOCKER_ID/complexfib-server
  - docker tag complexfib-worker $DOCKER_ID/complexfib-worker

  # Take those images and push them to docker hub
  - docker push $DOCKER_ID/complexfib-client
  - docker push $DOCKER_ID/complexfib-nginx
  - docker push $DOCKER_ID/complexfib-server
  - docker push $DOCKER_ID/complexfib-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: complex-fib
#   env: Complexfib-env
#   bucket_name: elasticbeanstalk-us-east-2-123456789
#   bucket_path: complex-fib
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY